// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlCT7SwHOXB5gvr6YjmtvNfx2srJFBkbY',
    appId: '1:46799448407:web:b8254fa4a0823103a9b612',
    messagingSenderId: '46799448407',
    projectId: 'cms-xaviers',
    authDomain: 'cms-xaviers.firebaseapp.com',
    storageBucket: 'cms-xaviers.appspot.com',
    measurementId: 'G-WS1D2E6F9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Aa1GUKgsfUCmdB5lTiluYMCUpDTn_2o',
    appId: '1:46799448407:android:bc898ae5cf09f8f8a9b612',
    messagingSenderId: '46799448407',
    projectId: 'cms-xaviers',
    storageBucket: 'cms-xaviers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACN0BewWAXbWbRl0xRsLjAIia6Y9rlAm4',
    appId: '1:46799448407:ios:aeb761a614d85dfaa9b612',
    messagingSenderId: '46799448407',
    projectId: 'cms-xaviers',
    storageBucket: 'cms-xaviers.appspot.com',
    iosClientId: '46799448407-gik0ac277p23rkfn3kf6r6ljpt4e9hvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACN0BewWAXbWbRl0xRsLjAIia6Y9rlAm4',
    appId: '1:46799448407:ios:aeb761a614d85dfaa9b612',
    messagingSenderId: '46799448407',
    projectId: 'cms-xaviers',
    storageBucket: 'cms-xaviers.appspot.com',
    iosClientId: '46799448407-gik0ac277p23rkfn3kf6r6ljpt4e9hvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
